ecommerceproject/cartapp/urls.py
from django.urls import path
from . import views

app_name = 'cartapp'

urlpatterns = [
    path('', views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('fullremove/<int:product_id>/', views.full_remove, name='full_remove')
]

ecommerceproject/ecommerceproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shopapp.urls')),
    path('search/', include('searchapp.urls')),
    path('cart/', include('cartapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecommerceproject/searchapp/urls.py
from django.urls import path, include
from . import views

app_name = 'searchapp'

urlpatterns = [
    path('', views.SearchResult, name='SearchResult'),
]

ecommerceproject/shopapp/urls.py
from . import views
from django.urls import path


app_name ='shopapp'


urlpatterns = [
    path('', views.AllProductCat, name='AllProductCat'),
    path('<slug:c_slug>/', views.AllProductCat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.Prodetails, name='ProdCatDetail')

]

ecommerceproject/cartapp/models.py
from django.db import models
from shopapp.models import Product
# Create your models here.


class Cart(models.Model):
    cart_id = models.CharField(max_length=250)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ('date_added',)

    def __str__(self):
        return '{}'.format(self.cart_id)


class CartItem(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity = models.IntegerField()
    Active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

ecommerceproject/searchapp/models.py
from django.db import models

# Create your models here.

ecommerceproject/shopapp/models.py
from django.db import models
from django.urls import reverse


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('shopapp:products_by_category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse('shopapp:ProdCatDetail',args=[self.category.slug,self.slug])

    def __str__(self):
        return '{}'.format(self.name)

ecommerceproject/cartapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from shopapp.models import Product
from .models import Cart, CartItem


# Create your views here.


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request,product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cartapp:cart_detail')

def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart,Active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_item=cart_items, total=total, counter=counter))


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()

    return redirect('cartapp:cart_detail')


def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cartapp:cart_detail')

ecommerceproject/searchapp/views.py
from django.shortcuts import render
from shopapp.models import Product
from django.db.models import Q


# Create your views here.


def SearchResult(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
    return render(request, 'search.html', {'query': query, 'products': products})

ecommerceproject/shopapp/views.py
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.shortcuts import render, get_object_or_404

from .models import Category, Product


# Create your views here.


def AllProductCat(request, c_slug=None):
    c_page = None
    products_list = None

    if c_slug is not None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.all().filter(category=c_page, available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
    paginator = Paginator(products_list, 1)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)

    return render(request, 'category.html', {'category': c_page, 'products': products_list})


def Prodetails(request, c_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=product_slug)
    except Exception as e:
        raise e
    return render(request, 'product.html', {'product': product})

ecommerceproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>


    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %} {% endblock %}</title>
</head>
<body >

<div class="container">
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
</div>
{% include 'footer.html' %}
<script src="{% static "js/popper.min.js" %}" ></script>

</body>
</html

ecommerceproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
<div>
{% block metadescription %}
   {% if category %}
      {{category.description|truncatewords:155}}
   {% else %}
      This is the cart page
   {% endif %}
{% endblock %}
</div>
<div>
{% block title  %}
   {% if category %}
      {{category.name}}
   {% else %}
       Cart
   {% endif %}
{% endblock %}
</div>
{% block content %}
{% if not cart_item %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your shopping cart is empty
        </h1>
        <br>
        <p class="text-center" >click here to continue shopping <a href="{% url 'shopapp:AllProductCat' %}" class="btn btn-secondary" ></a> </p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your shopping cart</h1>
        <br>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th colspan="5">
                    your items
                </th>
            </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_item %}
            <tr>
                <td>
                    <a href="#">
                        <img src="{{cart_item.product.image.url}}"  alt="" style="width:50px;height:50px;" class="float-left rounded custom-image">
                    </a>
                </td>


            <td class="text-left">
                {{cart_item.product.name}}
                <br>
                SKU: ${{cart_item.product.product_id}}
                <br>
                price: ${{cart_item.product.price}}
                <br>
                qty: {{cart_item.quantity}} x ${{cart_item}}

            </td>
            <td>
                ${{cart_item.sub_total}}
            </td>
          {% if cart_item.quantity < cart_item.product.stock %}
            <td>
                 <a href="{% url 'cartapp:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa fa-plus custom_icon"></i> </a>
                &nbsp;<a href="{% url 'cartapp:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i> </a>
                &nbsp;<a href="{% url 'cartapp:full_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-trash custom_icon"></i> </a>

            </td>
            {% else %}
            <td>
                &nbsp;<a href="{% url 'cartapp:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i> </a>
                &nbsp;<a href="{% url 'cartapp:full_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-trash custom_icon"></i> </a>


            </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-12 col-md-12 col-sm-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th>
                    checkout
                </th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    please recheck your cart before payment
                </td>
            </tr>
            <tr>
                <td class="text-left">
                    Your total amount:<strong>{{total}}</strong>
                </td>
            </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'shopapp:AllProductCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue shopping</a>
            <a href="{% url 'shopapp:AllProductCat' %}" class="btn btn-secondary btn-block my_custom_button">Payment</a>
        </div>

    </div>
</div>
{% endif %}
{% endblock %}

ecommerceproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
<div>
{% block metadescription %}
   {% if category %}
      {{category.description|truncatewords:155}}
   {% else %}
      Welcome to ABC Store
   {% endif %}
{% endblock %}
</div>
<div>
{% block title  %}
   {% if category %}
      {{category.name}}
   {% else %}
       Our new collections
   {% endif %}
{% endblock %}
</div>
<div class="row my_row_class">
    <div class="mx_auto">
{% block content %}
   {% if category %}
<div>
    <p> <a href="{% url 'shopapp:AllProductCat' %} ">Our collections </a></p>
</div>

    {% endif %}
   <div>

        {% if category %}
        <img class="my_image my_image_padding" src="{{ category.image.url }}" alt="{{ category.name }}">

   </div>
<br>
<div>
    <h1 class="text-center  my_title">{{category.name}}</h1>
    <p class="text-justify"> {{category.description}}</p>
</div>

    {% else %}
    <div class="container-fluid">
        <img  src="{% static 'image/banner.PNG' %}" alt="our product" width="800px" >
    </div>
<br>
<div>
    <h1>our product collection</h1>
    <p class="text-justify">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
</div>
{% endif %}

<div class="container">
    <div class="row mx_auto">
        {% for product in products %}
        <div class="my_bottom_margin  col-9 col-sm-12 col-md-4 col-lg-4"  style="margin-bottom:10px;">

            <div class="card text-center" style="height:400px;width:190px;">
        <a href="{{product.get_url}}"><img class="card_img_top my_image" src="{{product.image.url}}" alt="{{product.name}}" style="height:200px;width:170px;">
        </a>
        <div class="card-body">
   <h4>{{product.name}}</h4>
    <p>{{product.price}}</p>
        </div>
             </div>
    </div>

{% endfor %}
    </div>

    <div class="mx-auto">
        {% if product.paginator.num_pages > 1 %}
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>


{% endblock %}
</div>

ecommerceproject/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
  <p class="text-center">

    &copy;ABC company pvt ltd.All Rights Reserved

  </p>
</div>

ecommerceproject/templates/header.html
{% load static %}
<header>
     <center>
         <a href="{% url 'shopapp:AllProductCat' %}"></a>
         <img src="{% static 'image/logo.png' %}" width="350px">
     </center>
</header>

ecommerceproject/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="#">Home</a>
        </li>
        <li class="nav-item dropdown {% if 'shopapp' in request.path %}active{% endif %}">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           Shop
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'shopapp:AllProductCat' %}">All Products</a></li>
            {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
            {% endfor %}
          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cartapp:cart_detail' %}"><i class="fa fa-shopping-cart"></i>{{item_count}}</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" role="search" action="{% url 'searchapp:SearchResult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>
      </form>
    </div>
  </div>
</nav>

ecommerceproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
   {{product.description|truncatewords:155}}
{% endblock %}

{% block title %}
    {% if category %}
        {{product.name}}
    {% endif %}
{% endblock %}


{% block content %}
 <div class="row my_prod_row_class">
     <div class="mx_auto">
         <p><a href="{% url 'shopapp:AllProductCat' %}">Home</a>
         <a href="{{product.category.get_url}}">{{product.category}}</a>|{{product.name}}</p>
     </div>
     <br>
 </div>

<div class="container">
    <br>
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-md-6 text-center">
            <div style="min-width:18rem">
            <img class="my_image" src="{{product.image.url}}" alt="{{product.name}}">
            </div>
        </div>
    </div>
    <div class="col-12 col-md-12 col-md-12 col-lg-6">
        <div>
            <h1 class="my_prod_title">{{product.name}}</h1>
            <p>${{product.price}}</p>
            <p class="text-justify">{{product.description}}</p>
            {% if product.stock <= 0 %}
               <p class="text-justify"><b>Out Of Stock</b> </p>
            {% else %}
                <a href="{% url 'cartapp:add_cart' product.id %}" class="btn btn-secondary">Add To Cart</a>
            {% endif %}
        </div>
    </div>
</div>




{% endblock %}

ecommerceproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
   we have a variety of products
{% endblock %}
{% block title %}
   Search
{% endblock%}
{% block content %}
<div>
   <p class="text-center my_search_text">You have searched for <b>{{query}}</b></p>
</div>



<div class="container">
    <div class="row mx_auto">
        {% for product in products %}
        <div class="my_bottom_margin  col-9 col-sm-12 col-md-4 col-lg-4"  style="margin-bottom:10px;">

            <div class="card text-center" style="height:400px;width:190px;">
        <a href="{{product.get_url}}"><img class="card_img_top my_image" src="{{product.image.url}}" alt="{{product.name}}" style="height:200px;width:170px;">
        </a>
        <div class="card-body">
   <h4>{{product.name}}</h4>
    <p>{{product.price}}</p>
        </div>
             </div>
    </div>
     {% empty %}
       <div class="row mx-auto">
          <p class="text-center my_search_text">No result found</p>
       </div>
       {% endfor %}
    </div>
{% endblock %}
</div>